# Gitops

## Custom notebook image stream and minio

In this section we are going to create the same custom notebook image in RHOAI that we created in the previous sections, but in a Gitops way.

To do this we are going to edit the ai-accelerator code that we have forked.

The aim to is create an overlay named dev (similar to rhoai-fast) and creating a dev folder in the tenants section.

In this dev tenant we want to create an image stream for our custom notebook image present in quay.io. This way it shows up in our RHOAI notebook options and we can start a workbench with it.

The aim of this tutorial is to understand how we can utilize the AI Accelerator script and make edits to it based on the needs of our customers.

Make the following changes to the existing script. Some of these should already be done in the previous section:

* Add a dev folder to the bootstrap -> overlays folder. This should have a kustomization.yaml file

* Add a dev folder to the clusters -> overlays folder. This should have the kustomization.yaml, patch-application-manual-sync.yaml, patch-application-repo-revision.yaml and patch-applicationset-manual-sync.yaml files

* Add your forked branch to the patch-application-repo-revision.yaml file

* Add a dev folder to the components -> argocd -> apps -> overlays folder. This should have the kustomization.yaml, patch-cluster-config-app-of-apps.yaml, patch-configs-list.yaml, patch-operators-list.yaml and patch-tenants-applicationset.yaml files

* Add a dev folder to the tenants folder. In this create a new image-stream folder to add an image stream. Create the base and ovelays folder structure. The image stream should have the following specifications:

  * It should be created in the redhat-ods-applications namespace
[source,yaml]
----
namespace: redhat-ods-applications
----

  * The image should be imported as a Docker image as follows. Use the image that you created in quay.io:
[source,yaml]
----
from:
  kind: DockerImage
  name: 'quay.io/{quay_ID}/custom_notebook:latest'
importPolicy:
  importMode: Legacy
referencePolicy:
  type: Source
----

  * It should have the following labels so that it is visible as a custom image in RHOAI
[source,yaml]
----
labels:
  app.kubernetes.io/created-by: byon
  opendatahub.io/dashboard: 'true'
  opendatahub.io/notebook-image: 'true'
----

* To add a minio instance we can make use of resources that are already present in the ai-accelerator script. Create another folder named minio in the tenants section. Create the base and ovelays folder structure. In the base create the following kustomization file
[source,python]
----
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../../components/apps/minio/overlays/default
----

* Now check in the code and go to the ArgoCD page. Click on SYNC APPS.

* After everything is synced, go to the dev project in RHOAI and create a workbench from the custom image that we created. Then git clone parasol insuance repository https://github.com/rh-aiservices-bu/parasol-insurance.git. Go to lab-matrials/04 and run the 04-04-accident-recog.ipynb notebook. This will create the accident_detect.onnx file. Download this model file.

* Now we will add the code to serve this model with gitops. For this we will have to create a data connection to our minio bucket and then a model server and inference service. We also have to upload the model to our minio. Please refer to the multi-model-serving folder in the tenants -> ai-example path.



